### ISSUE TITLE
Redis client cannot connect to server

### ISSUE THREAD

**Issue by aparnakr** [enKryptIO/ethvm-socket-server#4]
When I run `npm run compose` it throws a cannot connect to `Error: connect ECONNREFUSED 127.0.0.1:6379`. This seems like the redis-client is unable to talk to the redis-server. Do you change the ports on which the server and port talk? 

It seems like there is no redis server running which is why the client is not able to connect?

**Comment by kvhnuke** [comment]
@niktrix can you please check
