### ISSUE TITLE
runtime errors on `npm run compose`

### ISSUE THREAD

**Issue by aparnakr** [enKryptIO/ethvm-socket-server#5]
I get the following errors when I run `npm run compose`: 

ERROR in ./src/vm/vmEngine.ts
[tsl] ERROR in /home/akrishnan/ethvm-socket-server/src/vm/vmEngine.ts(23,383)
      TS7018: Object literal's property 'inputs' implicitly has an 'any[]' type.

ERROR in ./src/addEvents.ts
[tsl] ERROR in /home/akrishnan/ethvm-socket-server/src/addEvents.ts(14,10)
      TS2304: Cannot find name 'VmEngine'.

ERROR in ./src/addEvents.ts
[tsl] ERROR in /home/akrishnan/ethvm-socket-server/src/addEvents.ts(134,85)
      TS2304: Cannot find name 'VmEngine'.

Would be happy to work on them. Just wondering if there is a version mismatch. Wondering if you have any guidance on how to go about fixing it.

**Comment by kvhnuke** [comment]
@niktrix can you please check

**Comment by aparnakr** [comment]
That doesn't fix it either. There are more issues that pop up as below 

ERROR in ./src/addEvents.ts
[tsl] ERROR in /home/akrishnan/ethvm-socket-server/src/addEvents.ts(14,10)
      TS2304: Cannot find name 'VmEngine'.

ERROR in ./src/addEvents.ts
[tsl] ERROR in /home/akrishnan/ethvm-socket-server/src/addEvents.ts(106,9)
      TS2554: Expected 1 arguments, but got 2.

ERROR in ./src/addEvents.ts
[tsl] ERROR in /home/akrishnan/ethvm-socket-server/src/addEvents.ts(141,85)
      TS2304: Cannot find name 'VmEngine'.
npm ERR! code ELIFECYCLE

**Comment by niktrix** [comment]
@aparnakr as per our discussion you are able to run this, hence closing this issue
